name: gw_course_students
channels:
  - microsoft
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - statsmodels=0.14.4
  - scipy=1.15.2
  - porespy=2.4.1
  - matplotlib=3.10.1
  - ipywidgets=8.1.5
  - pandas=2.2.3
  - pre-commit=4.2.0
  - elevation
  - numpy=1.26.4
  - jupyterlab=4.4.2
  - python=3.12
  - gdal=3.10.2
  - flopy=3.9.2
  - folium=0.19.5
  - rasterio=1.4.3
  - geopandas=1.0.1
  - scikit-image[version='<0.25.0']
  - contextily=1.6.2
  - matplotlib-scalebar=0.9.0
  - seaborn=0.13.2
  - ipympl=0.9.7
  - ipython=9.2.0
  - pyyaml=6.0.2
  - graphviz=12.2.1
  - psutil=7.0.0
  - python-graphviz=0.20.3
  - pykrige[version='1.7.2.*,1.7.2.*']
  - pyproj=3.7.1
  - shapely=2.1.0
  - yaml=0.2.5
  - requests=2.32.3
  - plotly=6.2.0
  - affine=2.4.0
  - rasterstats=0.20.0
