name: gw_course_development
channels:
  - microsoft
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - affine=2.4.0
  - contextily=1.6.2
  - elevation
  - flopy=3.9.2
  - gdal=3.10.2
  - geopandas=1.0.1
  - graphviz=12.2.1
  - ipympl=0.9.7
  - ipython=9.2.0
  - ipywidgets=8.1.5
  - jupyterlab=4.4.2
  - matplotlib=3.10.1
  - matplotlib-scalebar=0.9.0
  - numpy=1.26.4
  - pandas=2.2.3
  - plotly=6.2.0
  - porespy=2.4.1
  - pykrige=1.7.2
  - pre-commit=4.2.0
  - PyYAML=6.0.2
  - pykrige=1.7.2
  - python-graphviz=0.20.3
  - rasterio=1.4.3
  - rasterstats=0.20.0
  - requests=2.32.3
  - scikit-image[version='<0.25.0']
  - scipy=1.15.2
  - seaborn=0.13.2
  - shapely=2.1.0
  - statsmodels=0.14.4
  - yaml=0.2.5
