#!/usr/bin/env python3
"""Regenerate ``report_template.docx`` from ``report_template.md``.

The Word template is a *derived* file: ``report_template.md`` is the maintained
source. Because the .docx is binary it cannot be reviewed in a diff, so it is
regenerated by this script rather than by hand, and
``_SUPPORT/tests/test_report_template_consistency.py`` checks that what ships
actually matches the source.

This exists as a runnable script, not as a recipe in a docstring, because a
recipe that has to be retyped is a recipe that drifts. An earlier version lived
in a test docstring and could not be copy-pasted at all: the heredoc terminator
was indented, the body was indented into an ``IndentationError``, and the regex
escapes were doubled for the enclosing docstring, so a faithful paste silently
produced a mangled file that still passed the tests.

Usage::

    uv run python _SUPPORT/src/scripts/build_report_template_docx.py
    uv run python _SUPPORT/src/scripts/build_report_template_docx.py --check

``--check`` regenerates into a temporary file and compares, without writing:
exit 0 if the shipped .docx is current, 1 if it is stale.

Requires pandoc on PATH. pandoc is NOT a course dependency — students never run
this, only whoever edits the template does.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
TEMPLATE_DIR = REPO_ROOT / "PROJECT" / "workspace" / "template"
SOURCE_MD = TEMPLATE_DIR / "report_template.md"
TARGET_DOCX = TEMPLATE_DIR / "report_template.docx"


def build(target: Path) -> None:
    """Convert the Markdown template to .docx at ``target``."""
    if not shutil.which("pandoc"):
        sys.exit(
            "pandoc is not on PATH. Install it (https://pandoc.org) — it is needed "
            "only to regenerate this template, never by students."
        )
    if not SOURCE_MD.is_file():
        sys.exit(f"source template missing: {SOURCE_MD}")

    subprocess.run(
        ["pandoc", str(SOURCE_MD), "-o", str(target)],
        check=True,
    )


def _document_xml(path: Path) -> bytes:
    with zipfile.ZipFile(path) as zf:
        return zf.read("word/document.xml")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the shipped .docx is stale",
    )
    args = ap.parse_args()

    if args.check:
        if not TARGET_DOCX.is_file():
            print(f"STALE: {TARGET_DOCX.name} does not exist")
            return 1
        with tempfile.TemporaryDirectory() as tmp:
            candidate = Path(tmp) / "candidate.docx"
            build(candidate)
            if _document_xml(candidate) == _document_xml(TARGET_DOCX):
                print(f"OK: {TARGET_DOCX.name} matches {SOURCE_MD.name}")
                return 0
            print(
                f"STALE: {TARGET_DOCX.name} does not match {SOURCE_MD.name}.\n"
                f"Regenerate with:\n"
                f"  uv run python _SUPPORT/src/scripts/build_report_template_docx.py"
            )
            return 1

    build(TARGET_DOCX)
    print(f"wrote {TARGET_DOCX.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
