name: Check Notebook Dependencies

on:
  push:
    paths:
      - '**.ipynb'
      - '**.yml'
      - '**.yml'
  #pull_request:
  #  paths:
  #    - '**.ipynb'
  #    - 'requirements.txt'
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.12'
          environment-file: environment_development.yml
          activate-environment: gw_course_development
  
      - name: List the installed packages
        shell: bash -l {0}  # Important for conda to work properly
        run: conda list
  
      - name: Check notebook dependencies
        shell: bash -l {0}  # Important for conda to work properly
        run: python SUPPORT_REPO/src/scripts/check_notebook_dependencies.py